opensearch_dashboards.json, package.json, tsconfig.json, yarn.lock
Signed-off-by: YANG-DB <yang-db-dev@gmail.com>
Upgrade changes for 2.x
=> Merge 2.x changes into dashboards-query-workbench

release-notes/opensearch-query-workbench.release-notes-2.5.0.0.md
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
Adding Release notes 2.5.0
#19 
=> Adding Release notes 2.5.0

package.json
Signed-off-by: Joshua Li <joshuali925@gmail.com>
=> Rename plugin_helpers to plugin-helpers

.github/workflows/sql-workbench-test-build-workflow.yml, opensearch_dashboards.json, package.json
Signed-off-by: Rupal Mahajan <maharup@amazon.com>
Bump version to 2.6.0
=> Bump version to 2.6.0

release-notes/opensearch-query-workbench.release-notes-2.6.0.0.md
=> add release notes for 2.6 query workbench

.github/CODEOWNERS, MAINTAINERS.md
=> update maintainers and code owners

release-notes/opensearch-query-workbench.release-notes-2.8.0.0.md
=> Add release notes for 2.8

release-notes/opensearch-query-workbench.release-notes-1.3.10.0.md
=> add 1.3.10 release notes

release-notes/opensearch-query-workbench.release-notes-2.9.0.0.md
=> Add release notes for 2.9.0

package.json, yarn.lock
bump dependencies for tough-cookie, semver, word-wrap
=> bump dependencies for tough-cookie, semver, word-wrap

.github/workflows/backport.yml
=> update fail backport

release-notes/opensearch-query-workbench.release-notes-1.3.12.0.md
Add release notes for 1.3.12
release version 1.3.12 
=> Add release notes for 1.3.12

release-notes/opensearch-query-workbench.release-notes-2.10.0.0.md
Add release notes for 2.10.0
#96 
=> Add release notes for 2.10.0

package.json, yarn.lock
Resolution version bump that resolves security audit issue.
N/A
=> Upgrade cypress/request

release-notes/opensearch-query-workbench.release-notes-2.11.0.0.md
=> Release Notes 2.11

common/constants/index.ts, common/types/index.ts, common/utils/async_query_helpers.ts, public/components/Main/__snapshots__/main.test.tsx.snap, public/components/Main/main.tsx, public/components/SQLPage/DataSelect.tsx, public/components/SQLPage/__tests__/__snapshots__/acceleration_index_flyout.test.tsx.snap, public/components/SQLPage/__tests__/acceleration_index_flyout.test.tsx, public/components/SQLPage/acceleration_index_flyout.tsx, public/components/SQLPage/table_view.test.tsx, public/components/SQLPage/table_view.tsx, public/components/acceleration/create/__tests__/__snapshots__/create_acceleration.test.tsx.snap, public/components/acceleration/create/__tests__/utils.test.tsx, public/components/acceleration/create/create_acceleration.tsx, public/components/acceleration/create/utils.tsx, public/components/acceleration/selectors/__tests__/__snapshots__/index_setting_options.test.tsx.snap, public/components/acceleration/selectors/index_setting_options.tsx, public/components/acceleration/selectors/index_type_selector.tsx, public/components/acceleration/selectors/source_selector.tsx, public/components/acceleration/visual_editors/__tests__/query_builder.test.tsx, public/components/acceleration/visual_editors/materialized_view/group_by_tumble_expression.tsx, public/components/acceleration/visual_editors/query_builder.tsx, test/mocks/accelerationMock.ts
Make checkpoint mandatory, add watermark delay, minor UI fixes
1. Makes checkpoint mandatory
2. Add watermark delay option for materialized view
3. Minor UI fixes
4. Update Acc index flyout for mv support
5. Add test for acc index flyout
=> Make checkpoint mandatory, add watermark delay, minor UI fixes

common/constants/index.ts, common/utils/async_query_helpers.ts, public/components/SQLPage/CreateButton.tsx, public/components/SQLPage/table_view.tsx
fixed MV load bug
added mv create button
handled error case when post async query fails
=> UI-bug fixes, added create query for MV

public/components/Main/__snapshots__/main.test.tsx.snap, public/components/SQLPage/__tests__/__snapshots__/table_view.test.tsx.snap, public/components/SQLPage/table_view.scss, public/components/SQLPage/table_view.tsx, public/components/acceleration/selectors/index_type_selector.tsx, public/components/acceleration/selectors/source_selector.tsx
Fixed multiple toast for database
added fix for other database click
moved code to functions to reduce the repetition
#190 
=> added fix for loading spinner issue for other database

.github/CODEOWNERS, MAINTAINERS.md
=> Add Paul and Sumukh as maintainers and codeowners

opensearch_dashboards.json, package.json
=> version bump

.github/workflows/cypress-e2e-sql-workbench-test.yml
Add E2E Cypress workflow for sql workbench
* Backport #233 
=> [Backport 2.x] Add E2E Cypress workflow for sql workbench

.github/workflows/ftr-e2e-sql-workbench-test.yml
Add FTR e2e test workflow for dashboards query workbench
=> [CI/CD] Add FTR e2e test workflow for dashboards query workbench

.github/workflows/ftr-e2e-sql-workbench-test.yml
Add FTR workflow for sql workbench
* Backport #238 
=> [Backport 2.x] Add FTR workflow for sql workbench

package.json, public/components/QueryResults/__snapshots__/QueryResultsBody.test.tsx.snap, yarn.lock
Sync dependencies to the latest versions
* Backport #240 
=> [Backport 2.x] Sync dependencies to the latest versions

common/constants/index.ts
Add minutes option to acceleration
#205 
=> Add minutes option to acceleration

common/constants/index.ts, common/types/index.ts, public/components/Main/main.tsx, public/components/QueryResults/QueryResults.test.tsx, public/components/QueryResults/QueryResults.tsx, public/components/QueryResults/__snapshots__/QueryResults.test.tsx.snap, public/components/QueryResults/async_query_body.tsx, public/components/SQLPage/table_view.tsx, public/components/acceleration/create/utils.tsx, public/components/acceleration/selectors/index_type_selector.tsx, public/components/acceleration/selectors/source_selector.tsx, test/mocks/accelerationMock.ts
* added changes for cancel query not being able to cancel, added back ticks for default and other queries
Signed-off-by: sumukhswamy <sumukhhs@amazon.com>
* added lint check changes
Signed-off-by: sumukhswamy <sumukhhs@amazon.com>
* addressed comments
Signed-off-by: sumukhswamy <sumukhhs@amazon.com>
* addressed comments
Signed-off-by: sumukhswamy <sumukhhs@amazon.com>
* changed location of types
Signed-off-by: sumukhswamy <sumukhhs@amazon.com>
* updated snapshots
Signed-off-by: sumukhswamy <sumukhhs@amazon.com>
---------
Signed-off-by: sumukhswamy <sumukhhs@amazon.com>
Signed-off-by: Sumukh Swamy <sumukhhs@amazon.com>
(cherry picked from commit 886af5fac83e79d8c7562f7bc050ff59066b2491)
By submitting this pull …
=> [Backport 2.x] added changes for cancel query, added backticks (#256)

opensearch_dashboards.json
Add OSD react as required plugin
Was missed in original PR: https://github.com/opensearch-project/dashboards-query-workbench/pull/274
=> Add OSD react as required plugin

release-notes/opensearch-query-workbench.release-notes-2.14.0.0.md
Add release notes for 2.14
#295 
=> Add release notes for 2.14

release-notes/opensearch-query-workbench.release-notes-2.15.0.0.md
=> Release notes for 2.15.0.0

.github/workflows/cypress-e2e-sql-workbench-test.yml, .github/workflows/ftr-e2e-sql-workbench-test.yml
=> JDK update in workflows to version 21

release-notes/opensearch-query-workbench.release-notes-2.16.0.0.md
=> release-notes for 2.16

package.json, yarn.lock
Updated braces package to 3.0.3
Patches CVE CVE-2024-4068
=> Updated braces package to 3.0.3

release-notes/opensearch-query-workbench.release-notes-2.17.0.0.md
Add release notes for 2.17.0
https://github.com/opensearch-project/dashboards-query-workbench/issues/372
=> Add release notes for 2.17.0

release-notes/opensearch-query-workbench.release-notes-2.18.0.0.md
=> release notes for 2.18

package.json, yarn.lock
address CVE issue CVE-2024-4067.
=> [CVE] Address CVE-2024-4067 issue

release-notes/opensearch-query-workbench.release-notes-1.3.20.0.md
=> 1.3.20 release notes

release-notes/opensearch-query-workbench.release-notes-2.19.0.0.md
=> Add release notes for 2.19.0

public/components/SQLPage/sql_catalog_tree/s3_tree.tsx, public/components/SQLPage/sql_catalog_tree/s3_tree_helpers.tsx, public/dependencies/register_observability_dependencies.tsx
On clicking the accelerations in the side-tree the flyout is
https://github.com/user-attachments/assets/9d46ab3c-c696-4f0c-9b69-db826cb13252
https://github.com/opensearch-project/dashboards-query-workbench/issues/404
=> [Bug]Side tree flyout fix in async operations

public/components/SQLPage/sql_catalog_tree/s3_tree.tsx, public/components/SQLPage/sql_catalog_tree/s3_tree_helpers.tsx, public/dependencies/register_observability_dependencies.tsx
* flyout fix
* flyout fix
* linter changes
* linting changes
---------
=> [Backport 2.x]Side tree flyout fix in async operations (#448)

release-notes/opensearch-query-workbench.release-notes-3.0.0.0-alpha1.md
Add release notes for 3.0.0-aplha1
=> Add release notes for 3.0.0-aplha1

.github/workflows/cypress-e2e-sql-workbench-test.yml, .github/workflows/ftr-e2e-sql-workbench-test.yml, .github/workflows/link-checker.yml, .github/workflows/lint.yml, MAINTAINERS.md
Minor CI updates and workflow fixes
Derived from https://github.com/opensearch-project/dashboards-query-workbench/pull/458
=> Minor CI updates and workflow fixes

.cypress/utils/constants.js, public/components/Main/main.tsx, public/components/QueryResults/QueryResults.test.tsx, public/components/QueryResults/QueryResults.tsx, public/components/QueryResults/QueryResultsBody.test.tsx, public/components/QueryResults/QueryResultsBody.tsx, server/clusters/sql/sqlPlugin.js, server/routes/query.ts, server/services/QueryService.ts, server/services/utils/constants.ts, server/utils/constants.ts, test/mocks/mockData.ts
Remove download json feature, since the upstream SQL plugin isn't supporting this feature anymore. 
https://github.com/opensearch-project/sql/issues/3248, https://github.com/opensearch-project/sql/issues/3280
=> Remove download json feature

.github/workflows/cypress-e2e-sql-workbench-test.yml, .github/workflows/ftr-e2e-sql-workbench-test.yml, .github/workflows/verify-binary-installation.yml, opensearch_dashboards.json, package.json
=> Bump dashboards query workbench to version 3.0.0.0-beta1

release-notes/opensearch-query-workbench.release-notes-3.0.0.0-beta1.md
Add release notes for 3.0.0.0-beta1
https://github.com/opensearch-project/opensearch-build/issues/3747#issuecomment-2779448461
=> Release notes for 3.0.0.0-beta1

release-notes/opensearch-query-workbench.release-notes-3.1.0.0.md
Adding release notes for 3.1.0
#476 
=> Adding release notes for 3.1.0

package.json, release-notes/opensearch-dashboards-query-workbench.release-notes-3.3.0.0.md, yarn.lock
Fixing [CVE-2025-7783](https://github.com/advisories/GHSA-fjxv-7rqg-78g4)
=> Fixing CVE-2025-7783
