opensearch-project/dashboards-query-workbench

package.json
yarn.lock

Signed-off-by: Rupal Mahajan <maharup@amazon.com>
Added ansi-regex in resolutions for CVE-2021-3807
CVE-2021-3807

Upgrade ansi-regex to v5.0.1

---

package.json
yarn.lock

Signed-off-by: Rupal Mahajan <maharup@amazon.com>
Upgraded @types/hapi version to upgrade @sideway/formula 
```
=> Found "@sideway/formula@3.0.0"
info Reasons this module exists
- "@types#hapi-latest#@types#joi#joi" depends on it
- Hoisted from "@types#hapi-latest#@types#joi#joi#@sideway#formula"
info Disk size without dependencies: "36KB"
info Disk size with unique dependencies: "36KB"
info Disk size with transitive dependencies: "36KB"
info Number of shared dependencies: 0
Done in 0.20s.
```
CVE-2023-25166
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/m …

Upgrade hapi-latest to fix CVE-2023-25166

---

.github/workflows/sql-workbench-test-build-workflow.yml

The GitHub workflow uses the `engines` from OSD incorrectly. This change fixes that.

Fix Node.js and Yarn installation in CI

---

package.json
yarn.lock

Backporting  https://github.com/opensearch-project/dashboards-query-workbench/pull/60 to 2.x
- Added resolution for yaml v2.2.2
```
yarn why v1.22.19
[1/4] Why do we have the module "yaml"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "yaml@1.10.2"
info Reasons this module exists
- "husky#cosmiconfig" depends on it
- Hoisted from "husky#cosmiconfig#yaml"
info Disk size without dependencies: "640KB"
info Disk size with unique dependencies: "640KB"
info Disk size with transitive dependencies: "640KB"
info Number of shared dependencies: 0
Done in 0.21s.
```
- https://github.com/advisories/GHSA-f9xv-q969-pqx4
For …

[Backport 2.x] Add fix for CVE-2023-2251

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/draft-release-notes-config.yml
.github/workflows/backport.yml
.github/workflows/dco.yml
.github/workflows/delete_backport_branch.yml
.github/workflows/draft-release-notes-workflow.yml
.github/workflows/link-checker.yml
.github/workflows/sql-workbench-test-build-workflow.yml

Signed-off-by: Joshua Li <joshuali925@gmail.com>

Add github workflows

---

.gitignore
package.json
test/mocks/mockData.ts

CI was failing on JSON.parse, the mock data was not a valid json string

Use valid json for mock data in unit tests

---

package.json
yarn.lock

- Added tough-cookie v4.1.3 to resolution
- Added semver to resolution
https://github.com/advisories/GHSA-72xf-g2v4-qvf3
https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

[Backport 2.x] Upgrade tough-cookie and semver

---

common/constants/index.ts
common/index.ts
common/types/index.ts
opensearch_dashboards.json
package.json
public/components/acceleration/create/caution_banner_callout.tsx
public/components/acceleration/create/create_acceleration.tsx
public/components/acceleration/create/create_acceleration_header.tsx
public/components/acceleration/selectors/index_type_selector.tsx
public/components/acceleration/selectors/source_selector.tsx
public/components/acceleration/visual_editors/covering_index/covering_index_builder.tsx
public/components/acceleration/visual_editors/index_setting_options.tsx
public/components/acceleration/visual_editors/query_builder.tsx
public/components/acceleration/visual_editors/query_visual_editor.tsx
public/components/acceleration/visual_editors/skipping_index/add_fields_modal.tsx
public/components/acceleration/visual_editors/skipping_index/delete_fields_modal.tsx
public/components/acceleration/visual_editors/skipping_index/skipping_index_builder.tsx
public/plugin.ts

Introduces acceleration index creation flyout in workbench
NOTE: This code is still in high flux, will add tests in a follow up PR. 
#127 

Add table acceleration flyout

---

common/constants.ts
public/components/Main/__snapshots__/main.test.tsx.snap
public/components/Main/main.test.tsx
public/components/Main/main.tsx
public/components/SQLPage/SQLPage.tsx
public/components/SQLPage/TableView.tsx
public/components/SQLPage/__snapshots__/SQLPage.test.tsx.snap
public/components/app.tsx
public/utils/constants.ts
test/mocks/mockData.ts

added changes for flint 
sidebar changes with create and Data-connections tab added
added tables names as indexed

Define tables

---

common/constants/index.ts
public/components/Main/__snapshots__/main.test.tsx.snap
public/components/Main/main.tsx
public/components/SQLPage/CreateButton.tsx
public/components/SQLPage/SQLPage.tsx
public/components/SQLPage/TableView.tsx

loading and create button changes

Design changes for the sidebar and update to create button

---

public/components/acceleration/selectors/index_type_selector.tsx

Load table fields for acceleration index flyout
Assumes backend response form https://github.com/opensearch-project/sql/issues/2210: 
```
const result  = [
{ col_name: '@timestamp', data_type: 'timestamp' },
{ col_name: 'clientip', data_type: 'string' },
{ col_name: 'request', data_type: 'string' },
{ col_name: 'status', data_type: 'int' },
{ col_name: 'size', data_type: 'int' },
{ col_name: 'year', data_type: 'int' },
{ col_name: 'month', data_type: 'int' },
{ col_name: 'day', data_type: 'int' },
{ col_name: 'year', data_type: 'int' },
{ col_name: 'month', data_type: 'int' },
{ col_name: 'day', data_type: 'int' },
];
```
#127 
For more information on following Developer …

Load table fields for acceleration index flyout

---

common/constants/index.ts
public/components/Main/__snapshots__/main.test.tsx.snap
public/components/Main/main.tsx
public/components/PPLPage/PPLPage.tsx
public/components/PPLPage/__snapshots__/PPLPage.test.tsx.snap
public/components/SQLPage/CreateButton.tsx
public/components/SQLPage/SQLPage.tsx
public/components/SQLPage/TableView.tsx
public/components/SQLPage/acceleration_index_flyout.tsx
public/components/SQLPage/utils.tsx
public/components/acceleration/selectors/index_type_selector.tsx
public/components/acceleration/visual_editors/query_builder.tsx
test/mocks/accelerationMock.ts

Adding minor updates to acceleration ui
#127 

Adding minor updates and bug fixes

---

common/constants/index.ts
public/components/Main/__snapshots__/main.test.tsx.snap
public/components/Main/main.tsx
public/components/QueryResults/QueryResults.tsx
public/components/QueryResults/QueryResultsBody.test.tsx
public/components/QueryResults/QueryResultsBody.tsx
public/components/QueryResults/__snapshots__/QueryResults.test.tsx.snap
public/components/QueryResults/__snapshots__/QueryResultsBody.test.tsx.snap
public/components/SQLPage/CreateButton.tsx
public/components/SQLPage/SQLPage.test.tsx
public/components/SQLPage/SQLPage.tsx
public/components/SQLPage/__snapshots__/SQLPage.test.tsx.snap
public/components/acceleration/create/__tests__/__snapshots__/create_acceleration.test.tsx.snap
public/components/acceleration/create/__tests__/utils.test.tsx
public/components/acceleration/selectors/__tests__/__snapshots__/define_index_options.test.tsx.snap
public/components/acceleration/selectors/define_index_options.tsx

Adding bug fixes for SQL UI buttons
1. Show create Button only on S3 datasources
2. Show explain and download buttons only on OpenSearch datasource
3. Remove text editor disabling 
4. Update index name regex
#122 

Bug fixes for SQL UI buttons

---

common/constants/index.ts
common/types/index.ts
public/components/Main/main.tsx
public/components/SQLPage/SQLPage.tsx
public/components/acceleration/create/__tests__/__snapshots__/create_acceleration.test.tsx.snap
public/components/acceleration/create/__tests__/__snapshots__/create_acceleration_header.test.tsx.snap
public/components/acceleration/selectors/__tests__/__snapshots__/index_setting_options.test.tsx.snap
public/components/acceleration/selectors/__tests__/__snapshots__/index_type_selector.test.tsx.snap
public/components/acceleration/selectors/__tests__/__snapshots__/source_selector.test.tsx.snap
public/components/acceleration/selectors/index_setting_options.tsx
public/components/acceleration/selectors/source_selector.tsx
public/components/acceleration/visual_editors/__tests__/query_builder.test.tsx
public/components/acceleration/visual_editors/query_builder.tsx
test/mocks/accelerationMock.ts

1. Add materialized view option
2. remove fill from accelerate table button
3. Add manual refresh option
4. Update copy for data sources
5. Fix redirection issue to acceleration flyout
6. Update tests
#127 
Depends on https://github.com/opensearch-project/opensearch-spark/pull/73

Add materlized views, manual refresh option and minor fixes

---

common/types/index.ts
common/utils/async_query_helpers.ts
public/components/Main/__snapshots__/main.test.tsx.snap
public/components/Main/main.tsx
public/components/SQLPage/__snapshots__/table_view.test.tsx.snap
public/components/SQLPage/table_view.test.tsx
public/components/SQLPage/table_view.tsx
test/mocks/mockData.ts

design changes for loading tree elements, changed the banner, updated tests

---

common/constants/index.ts
common/utils/async_query_helpers.ts
public/components/Main/main.tsx
public/components/acceleration/create/__tests__/__snapshots__/create_acceleration.test.tsx.snap
public/components/acceleration/create/__tests__/utils.test.tsx
public/components/acceleration/create/create_acceleration.tsx
public/components/acceleration/selectors/__tests__/__snapshots__/define_index_options.test.tsx.snap
public/components/acceleration/selectors/__tests__/__snapshots__/index_setting_options.test.tsx.snap
public/components/acceleration/selectors/define_index_options.tsx
public/components/acceleration/selectors/index_setting_options.tsx
public/components/acceleration/selectors/index_type_selector.tsx
public/components/acceleration/selectors/source_selector.tsx
public/components/acceleration/visual_editors/materialized_view/add_column_popover.tsx
public/components/acceleration/visual_editors/materialized_view/column_expression.tsx
public/components/acceleration/visual_editors/materialized_view/group_by_tumble_expression.tsx
public/components/acceleration/visual_editors/materialized_view/materialized_view_builder.tsx

1. Remove clearing session from storage
2. Update acceleration flytout primary shard count to 5
3. Fix MV index preview name in acceleration flyout
4. Clear query and result window on datasource change
5. Fix MV tumble validation issue, increase form width
6. Update S3 regex to allow buckets
7. Add toasts for failure response in acceleration flyout
8. Update tests
#127 

Session update, minor fixes for acceleration flyout

---

public/components/acceleration/visual_editors/__tests__/query_builder.test.tsx
public/components/acceleration/visual_editors/query_builder.tsx
test/mocks/accelerationMock.ts

1. Add backticks to columns for acceleration flyout
2. remove redundant checkpoint for manual refresh
#127 

Add backticks and remove ckpt for manual refresh in acceleration flyout

---

public/components/Main/__snapshots__/main.test.tsx.snap
public/components/SQLPage/table_view.tsx

Fix error handling for user w/o indices access and sql/ppl access 
#193 

Fix error handling for user w/o proper permissions

---

release-notes/opensearch-query-workbench.release-notes-2.11.1.0.md

Release-notes/2.11.1

---

babel.config.js

babel config change

---

.github/workflows/cypress-e2e-sql-workbench-test.yml

Add E2E Cypress workflow for sql workbench
Reference to: https://github.com/opensearch-project/dashboards-query-workbench/actions/runs/7216048968/job/19661506355?pr=233#step:20:134
```
The response we got was:
Status: 406 - Not Acceptable
Headers: {
"content-type": "application/json; charset=utf-8",
"osd-name": "fv-az1269-175",
"cache-control": "private, no-cache, no-store, must-revalidate",
"vary": "accept-encoding",
"content-encoding": "gzip",
"date": "Fri, 15 Dec 2023 00:15:57 GMT",
"connection": "keep-alive",
"keep-alive": "timeout=120",
"transfer-encoding": "chunked"
}
Body: {
"error": "Content-Type header [application/x-www-form-urlencoded] is not supported",
"status": 406
}
```
The above matches the expected failure on #232 
* Relate #232 
By submitting this pull request, I confirm …

[CI/CD] Add E2E Cypress workflow for sql workbench

---

package.json
public/components/QueryResults/__snapshots__/QueryResultsBody.test.tsx.snap
yarn.lock

Due to the failure of version conflict for security dashboards plugin's distribution build: https://github.com/opensearch-project/security-dashboards-plugin/blob/7cad47c38478646cd96f0eb1623b77acd853b803/package.json#L30
* Relate https://github.com/opensearch-project/dashboards-query-workbench/issues/240 

Sync dependencies to the latest versions

---

release-notes/opensearch-query-workbench.release-notes-2.12.0.0.md

Add release notes for 2.12 release

---

.github/workflows/cypress-e2e-sql-workbench-test.yml
.github/workflows/ftr-e2e-sql-workbench-test.yml
.github/workflows/lint.yml
.github/workflows/sql-workbench-test-build-workflow.yml

On behalf of the change in dashboards core: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5675. We need to add `--single-version=loose` flag during the bootstrap step in our CI to manipulate the behavior of single-version validation. 
* Resolve the CI failure: https://github.com/opensearch-project/dashboards-observability/actions/runs/7964135017/job/21741091909?pr=1447#step:16:231

[CI/CD] Add single version flag during bootstrap to fix version conflicts

---

.github/workflows/verify-binary-installation.yml

I have observed some issues within other plugins of issues being only caught at run time. This is because several things can go wrong during the build process, which may not be caught in a dev setup. This adds a workflow to verify that building and installing into OSD works on every PR.
Related issues:
https://github.com/opensearch-project/security-dashboards-plugin/issues/1709
https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/875
https://github.com/opensearch-project/dashboards-observability/pull/309
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5952
For more information on following …

Add workflow to verify binary install

---

.github/workflows/cypress-e2e-sql-workbench-test.yml
.github/workflows/ftr-e2e-sql-workbench-test.yml

FTR repos/functional tests are failing to run due to an issue with dashboards coming up healthy within 10 minutes. Not sure what's the issue. 

Manual bump to 2.13 for workflows

---

common/utils/async_query_helpers.ts
public/components/Main/__snapshots__/main.test.tsx.snap
public/components/Main/main.tsx
public/components/SQLPage/sql_catalog_tree/os_tree.tsx
public/components/SQLPage/sql_catalog_tree/s3_tree.tsx
release-notes/opensearch-query-workbench.release-notes-2.13.0.0.md

Add empty tree state for SQL sidebar
* fixes empty state in side tree for opensearch and s3 datasource
* Copy update for text in loading and empty state
* Stops polling on cancel query

Add empty tree state for SQL sidebar

---

public/components/SQLPage/sql_catalog_tree/s3_tree.tsx
public/components/SQLPage/sql_catalog_tree/s3_tree_helpers.tsx
release-notes/opensearch-query-workbench.release-notes-2.13.0.0.md

Catch no database errors
* Fixes clearing databases when the tree is refreshed
* Catches no databases/datasources  in tree error from cache manager

Catch no database found errors from cache manager

---

public/components/SQLPage/sql_catalog_tree/__tests__/__snapshots__/catalog_s3_loaded.test.tsx.snap
public/components/SQLPage/sql_catalog_tree/__tests__/__snapshots__/catalog_s3_loading.test.tsx.snap
public/components/SQLPage/sql_catalog_tree/__tests__/__snapshots__/catalog_tree.test.tsx.snap
public/components/SQLPage/sql_catalog_tree/__tests__/catalog_s3_loaded.test.tsx
public/components/SQLPage/sql_catalog_tree/__tests__/catalog_s3_loading.test.tsx
public/components/SQLPage/sql_catalog_tree/__tests__/catalog_tree.test.tsx
public/components/SQLPage/sql_catalog_tree/s3_tree.tsx
public/dependencies/register_observability_dependencies.tsx

Fix initial load from cache for S3 tree 
* Fixes initial load issue of not loading databases for the S3 tree in workbench
* Updates the tree scss to not overlap tree elements
* Keep workbench dependency on observability 

Fix initial load from cache for S3 tree

---

public/components/Main/__snapshots__/main.test.tsx.snap
public/components/Main/main.test.tsx
release-notes/opensearch-query-workbench.release-notes-2.15.0.0.md

Fixed flakey unit tests for query-workbench

Flakey unit tests fix

---

opensearch_dashboards.json
public/components/Main/main.tsx

added version decoupling for neo MDS support

---

opensearch_dashboards.json
public/components/Main/main.tsx

* added version decoupling for neo MDS suypport
* linter changes
* updated manifest file
* updated lowest version to 1
---------

[Backport 2.x] added version decoupling for neo MDS support (#353)

---

common/utils/legacy_route_helper.tsx
opensearch_dashboards.json
public/application.tsx
public/components/Main/main.tsx
public/components/app.tsx
public/plugin.ts

This change migrates query workbench to dev tools for the navigation changes planned for 2.16. The way the selectedMDSDataConnectionId was passed needed to be updated to allow dev tools to correctly find data sources.
Working with MDS:
https://github.com/user-attachments/assets/d0e02549-c299-40de-b4fd-8de5b15f4d07
Working with Flint:
[FlintTest.mov.zip](https://github.com/user-attachments/files/16185668/FlintTest.mov.zip)
There is an existing issue I outlined in https://github.com/opensearch-project/dashboards-query-workbench/issues/348. But testing with Flint(using dashboards-observability prior to the https://github.com/opensearch-project/dashboards-observability/commit/19d68b2d443458c3fdb1bd0fe035bf823111015b commit) seems to keep all functionality working correctly.
By submitting this …

Moving Query Workbench to Dev Tools

---

common/utils/legacy_route_helper.tsx
opensearch_dashboards.json
public/application.tsx
public/components/Main/main.tsx
public/components/app.tsx
public/plugin.ts

* Migrate to devTools
Signed-off-by: Adam Tackett <tackadam@amazon.com>
* MDS working changed how ID passed
Signed-off-by: Adam Tackett <tackadam@amazon.com>
* Chagned name to dataSourceMDSId
Signed-off-by: Adam Tackett <tackadam@amazon.com>
* remove console log
Signed-off-by: Adam Tackett <tackadam@amazon.com>
* add support for backward URLs
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
* update nav coditionally and set breadcrumbs
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
* fix lint error
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
* update breadcrumb only when nav is enabled
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
* fix URL for new nav is disabled
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
---------
Signed-off-by: Adam Tackett …

[Backport 2.x] Moving Query Workbench to Dev Tools (#349)

---

public/components/Main/main.tsx
public/components/acceleration/selectors/source_selector.tsx

Side tree was not loading in the case of ols nav as the MDS id was not being passed, 
after Fix
There was no ID added from this pr which was causing the page to not refresh
https://github.com/opensearch-project/dashboards-query-workbench/pull/349

[Bug]fix for missing id in old nav

---

public/components/Main/main.tsx
public/components/app.tsx

1. Fix url redirection
2. Add default render path when there is basePath
closing : https://github.com/opensearch-project/dashboards-query-workbench/pull/381
(Support for dev tools under modal pop out)
As we will make dev tools as a full page modal when new nav toggle is turned on, we will use MemoryRouter to replace HashRouter in our page to avoid modifying the hosted page' hash. And this change will impact search relevance functionality.
And this PR adds a default path when there is no '/' route.
For more details please take a look on the comment: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7938#discussion_r1738383931.
Tested url paths:
path={`/${basePath}/:dataSource`}
path={`/${basePath}/accelerate/:dataSource`}
path="/"
path={`/${basePath}`}
Old Navigation: …

[Bug] Fix url redirection, add default render path

---

package.json
release-notes/opensearch-query-workbench.release-notes-2.17.0.0.md
yarn.lock

Bump the lint-staged from 13.1.0 to 15.2.10
[CVE-2024-4067](https://github.com/advisories/GHSA-952p-6rrq-rcjv)

[CVE] Bump the lint-staged from 13.1.0 to 15.2.10

---

public/components/app.tsx

Fix workbench routes to support modal mounting
* Fixes modal load for workbench via dev tools modal.
https://github.com/user-attachments/assets/b1289228-7edc-440c-a41f-51621e196341
* Persists flint non-MDS navigation flows
https://github.com/user-attachments/assets/ef159359-52d2-4b36-b766-bd2bbcf96aa3

Fix workbench routes to support modal mounting

---

server/routes/query.ts
server/services/QueryService.ts

r MDS plugins needed error handling to not return response as okay

[Bug]added error handling for api calls

---

.github/workflows/cypress-e2e-sql-workbench-test.yml
.github/workflows/ftr-e2e-sql-workbench-test.yml
.github/workflows/sql-workbench-test-build-workflow.yml
package.json
yarn.lock

Downgrade cypress version to 12.17.4 to match Opensearch Dashboards and upgrade artifact action to v4
Query workbench plugin is failing in dashboards 2.19.0 distribution build because of different cypress versions:
```
ERROR [single_version_dependencies] Multiple version ranges for the same dependency
were found declared across different package.json files. Please consolidate
those to match across all package.json files. Different versions for the
same dependency is not supported.
If you have questions about this please reach out to the operations team.
The conflicting dependencies are:
cypress
12.17.4 => opensearch-dashboards
^13.6.0 => opensearch-query-workbench
```
By submitting this pull request, I confirm that my contribution is made under the …

Downgrade cypress to 12.17.4

---

.github/workflows/cypress-e2e-sql-workbench-test.yml
.github/workflows/ftr-e2e-sql-workbench-test.yml
.github/workflows/sql-workbench-test-build-workflow.yml
package.json
yarn.lock

[manual Backport 2.x]Downgrade cypress to 12.17.4 (#430)
https://github.com/opensearch-project/dashboards-query-workbench/pull/430
* downgrade cypress to 12.17.4
* update artifact action to v4
* update all artifact actions to v4
---------

[Backport 2.x]Downgrade cypress to 12.17.4 (#430)

---

release-notes/opensearch-query-workbench.release-notes-2.19.0.0.md
yarn.lock

Update yarn.lock for bumping cross-spawn to 7.0.5

Update yarn.lock for cross-spawn

---

.github/workflows/cypress-e2e-sql-workbench-test.yml
.github/workflows/ftr-e2e-sql-workbench-test.yml
.github/workflows/verify-binary-installation.yml
opensearch_dashboards.json
package.json

Bump dashboards query workbench to version 3.0.0.0-alpha1
https://github.com/opensearch-project/dashboards-query-workbench/issues/97
- ~~[ ] New functionality includes testing.~~
- ~~[ ] All tests pass, including unit test, integration test and doctest~~
- ~~[ ] New functionality has been documented.~~
- ~~[ ] New functionality has javadoc added~~
- ~~[ ] New functionality has user manual doc added~~

Bump dashboards query workbench to version 3.0.0.0-alpha1

---

.github/workflows/cypress-e2e-sql-workbench-test.yml
.github/workflows/ftr-e2e-sql-workbench-test.yml

Add job scheduler to workbench CI, SQL plugin recently added this as an dependency leading the observability CI failing waiting for Job scheduler plugin. Related upstream PR: https://github.com/opensearch-project/sql/pull/2834
https://github.com/opensearch-project/dashboards-query-workbench/issues/97

update CIs to install job-scheduler plugin
